"""Provider profiles for auditability and downstream tool ownership."""

from __future__ import annotations

from .base import ProviderProfile


PROVIDER_PROFILES: dict[str, ProviderProfile] = {
    "coingecko": ProviderProfile(
        name="COINGECKO",
        category="market data",
        purpose="Crypto prices, rankings, market caps, and historical crypto market context.",
        auth_method="API key header",
        env_var="COINGECKO_API_KEY",
        internal_tools=["get_crypto_prices", "get_market_overview", "get_portfolio_valuation"],
        benefiting_agents=["market_researcher", "portfolio_monitor", "risk_manager", "strategy_agent"],
        fallback_overlap=["coinmarketcap"],
    ),
    "coinmarketcap": ProviderProfile(
        name="COINMARKETCAP",
        category="market data",
        purpose="Crypto quotes, listings, and market-wide crypto intelligence.",
        auth_method="API key header",
        env_var="COINMARKETCAP_API_KEY",
        internal_tools=["get_crypto_prices", "get_market_overview", "get_asset_rankings"],
        benefiting_agents=["market_researcher", "portfolio_monitor", "risk_manager", "strategy_agent"],
        fallback_overlap=["coingecko"],
    ),
    "twelvedata": ProviderProfile(
        name="TWELVEDATA",
        category="market/time-series data",
        purpose="OHLCV, indicators, and cross-asset time-series data.",
        auth_method="API key query param",
        env_var="TWELVEDATA_API_KEY",
        internal_tools=["get_ohlcv", "get_indicator_snapshot", "get_volatility_metrics", "get_correlation_inputs"],
        benefiting_agents=["strategy_agent", "risk_manager", "market_researcher", "portfolio_monitor"],
    ),
    "fred": ProviderProfile(
        name="FRED",
        category="macro data",
        purpose="Macro time series, metadata, and observation history for regime and event-risk analysis.",
        auth_method="API key query param",
        env_var="FRED_API_KEY",
        internal_tools=[
            "get_macro_series",
            "get_macro_observations",
            "get_macro_regime_summary",
            "get_event_risk_macro_context",
        ],
        benefiting_agents=["market_researcher", "risk_manager", "strategy_agent"],
    ),
    "cryptopanic": ProviderProfile(
        name="CRYPTOPANIC",
        category="crypto news",
        purpose="Crypto-native news and narrative aggregation.",
        auth_method="API key query param",
        env_var="CRYPTOPANIC_API_KEY",
        internal_tools=["get_crypto_news", "get_event_risk_summary"],
        benefiting_agents=["market_researcher", "risk_manager"],
        fallback_overlap=["newsapi"],
    ),
    "newsapi": ProviderProfile(
        name="NEWSAPI",
        category="general news",
        purpose="General news, macro news, and broad event risk.",
        auth_method="API key header",
        env_var="NEWS_API_KEY",
        internal_tools=["get_general_news", "get_event_risk_summary"],
        benefiting_agents=["market_researcher", "risk_manager"],
        fallback_overlap=["cryptopanic"],
    ),
    "etherscan": ProviderProfile(
        name="ETHERSCAN",
        category="onchain data",
        purpose="Wallet activity, token transfers, and contract activity across EVM chains.",
        auth_method="API key query param",
        env_var="ETHERSCAN_API_KEY",
        internal_tools=["get_onchain_wallet_data", "get_wallet_transactions", "get_token_activity"],
        benefiting_agents=["market_researcher", "portfolio_monitor", "risk_manager", "strategy_agent"],
        fallback_overlap=["nansen"],
    ),
    "lunarcrush": ProviderProfile(
        name="LUNARCRUSH",
        category="sentiment/social",
        purpose="Social sentiment, engagement spikes, and narrative trends.",
        auth_method="Bearer token",
        env_var="LUNARCRUSH_API_KEY",
        internal_tools=["get_social_sentiment", "get_social_spike_alerts"],
        benefiting_agents=["market_researcher", "risk_manager", "strategy_agent"],
    ),
    "nansen": ProviderProfile(
        name="NANSEN",
        category="advanced onchain intelligence",
        purpose="Smart money analytics, wallet labels, holdings, and advanced onchain intelligence.",
        auth_method="API key header",
        env_var="NANSEN_API_KEY",
        internal_tools=["get_smart_money_flows", "get_labeled_wallet_activity", "get_onchain_signal_summary"],
        benefiting_agents=["market_researcher", "risk_manager", "portfolio_monitor", "strategy_agent"],
        fallback_overlap=["etherscan"],
    ),
    "bitmart_public": ProviderProfile(
        name="BITMART_PUBLIC",
        category="market data / derivatives",
        purpose="Free public BitMart futures REST endpoints: futures order book depth, funding rates, open interest, and liquidation pressure proxy. No API key required.",
        auth_method="none",
        env_var="BITMART_PUBLIC_NO_KEY_REQUIRED",
        internal_tools=["get_order_book", "get_funding_rates", "get_liquidation_zones"],
        benefiting_agents=["market_researcher", "risk_manager", "strategy_agent", "portfolio_monitor"],
        fallback_overlap=[],
    ),
    "bitmart": ProviderProfile(
        name="BITMART",
        category="execution",
        purpose="Spot execution, balances, order history, trade history, and execution status via CCXT.",
        auth_method="API key, secret, and memo",
        env_var="BITMART_API_KEY",
        internal_tools=[
            "get_exchange_balances",
            "get_open_orders",
            "place_order",
            "cancel_order",
            "get_order_history",
            "get_trade_history",
            "get_execution_status",
        ],
        benefiting_agents=["orchestrator_trader", "portfolio_monitor", "risk_manager"],
    ),
    "defillama": ProviderProfile(
        name="DEFILLAMA",
        category="defi intelligence",
        purpose="Free DeFi protocol, chain, DEX, fee, and regime intelligence from DefiLlama's public API.",
        auth_method="No auth (free public API)",
        env_var="",
        internal_tools=[
            "get_defi_protocols",
            "get_defi_protocol_details",
            "get_defi_chain_overview",
            "get_defi_yields",
            "get_defi_dex_overview",
            "get_defi_fees_overview",
            "get_defi_open_interest",
            "get_defi_regime_summary",
        ],
        benefiting_agents=["market_researcher", "risk_manager", "strategy_agent"],
    ),
    "telegram_notifications": ProviderProfile(
        name="TELEGRAM",
        category="notifications",
        purpose="Outbound operator-facing trade, risk, summary, and execution notifications via Telegram Bot API.",
        auth_method="Bot token plus fixed chat id",
        env_var="TELEGRAM_BOT_TOKEN",
        internal_tools=[
            "send_notification",
            "send_trade_alert",
            "send_risk_alert",
            "send_daily_summary",
            "send_execution_update",
        ],
        benefiting_agents=["orchestrator_trader", "portfolio_monitor", "risk_manager", "market_researcher"],
        fallback_overlap=["slack_notifications"],
    ),
    "slack_notifications": ProviderProfile(
        name="SLACK",
        category="notifications",
        purpose="Outbound operator-facing trade, risk, summary, and execution notifications via Slack incoming webhook.",
        auth_method="Incoming webhook URL",
        env_var="SLACK_WEBHOOK_URL",
        internal_tools=[
            "send_notification",
            "send_trade_alert",
            "send_risk_alert",
            "send_daily_summary",
            "send_execution_update",
        ],
        benefiting_agents=["orchestrator_trader", "portfolio_monitor", "risk_manager", "market_researcher"],
        fallback_overlap=["telegram_notifications"],
    ),
}
