// Inject Chronos-2 Pine Script forecasts into TradingView
const { spawn } = require('child_process');
const fs = require('fs');
const proc = spawn('node', ['src/server.js'], { stdio: ['pipe','pipe','pipe'], cwd: '/Users/openclaw/Coding/tradingview-mcp-jackson' });

let msgId = 1, buf = '';
const pending = new Map();

proc.stdout.on('data', (data) => {
  buf += data.toString();
  const lines = buf.split('\n');
  buf = lines.pop();
  for (const line of lines) {
    if (!line.trim()) continue;
    try {
      const obj = JSON.parse(line);
      if (obj.id && pending.has(obj.id)) { pending.get(obj.id).resolve(obj); pending.delete(obj.id); }
    } catch(e) {}
  }
});
proc.stderr.on('data', () => {});

function call(method, params) {
  return new Promise((resolve, reject) => {
    const id = msgId++;
    pending.set(id, { resolve, reject });
    proc.stdin.write(JSON.stringify({jsonrpc:'2.0', id, method, params}) + '\n');
    setTimeout(() => { if (pending.has(id)) { pending.delete(id); reject(new Error('timeout: '+method)); }}, 30000);
  });
}

function tv(name, args) {
  return call('tools/call', { name, arguments: args || {} })
    .then(r => { const t = r.result?.content?.[0]?.text || r.result; try { return JSON.parse(t); } catch(e) { return t; } });
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

const forecast = JSON.parse(fs.readFileSync('/Users/openclaw/.hermes/scripts/chronos_forecast.json'));

// Build Pine Script for Chart 1 — ETH active bot view with Chronos-2
function buildETHPine(fc) {
  const eth = fc.ETH;
  const sc = eth.scenarios;
  const last = eth.last;
  
  // Generate forecast value arrays for Pine
  const medians = sc.map(s => s.median.toFixed(2)).join(', ');
  const lows    = sc.map(s => s.low.toFixed(2)).join(', ');
  const highs   = sc.map(s => s.high.toFixed(2)).join(', ');
  const trend12 = sc[11].median > last ? '▲ BULLISH' : '▼ BEARISH';
  const pct12   = ((sc[11].median - last) / last * 100).toFixed(2);
  const triggerMsg = last >= 2350 ? '🔥 ABOVE TRIGGER — BOT B SHOULD BE ACTIVE' : `⏳ ${(2350 - last).toFixed(0)} below $2,350 trigger`;

  return `//@version=5
indicator("🤖 Hermes — ETH Bot B + Chronos-2 Forecast", overlay=true, max_lines_count=50, max_labels_count=50)

// ══ CHRONOS-2 FORECAST DATA (live run ${new Date().toISOString().slice(0,16)}) ══
// Last close: $${last}  |  48h outlook: ${trend12} ${pct12}%
// Forecast generated by Amazon Chronos-2 (chronos-t5-tiny, 100 samples)

var float[] med_fc  = array.from(${medians})
var float[] low_fc  = array.from(${lows})
var float[] high_fc = array.from(${highs})

// ══ BOT B KEY LEVELS ══
bot_trigger  = 2350.0
bot_grid_top = 2500.0
bot_grid_bot = 2150.0
bot_sl       = 2050.0
bot_tp       = 2580.0

// Draw bot levels
hline(bot_trigger,  "🔥 Trigger $2,350",  color=color.new(color.yellow, 0),  linestyle=hline.style_dashed, linewidth=2)
hline(bot_grid_top, "Grid Top $2,500",    color=color.new(color.green,  40), linestyle=hline.style_dashed, linewidth=1)
hline(bot_grid_bot, "Grid Low $2,150",    color=color.new(color.orange, 40), linestyle=hline.style_dashed, linewidth=1)
hline(bot_sl,       "🛑 Stop Loss $2,050",color=color.new(color.red,    0),  linestyle=hline.style_solid,  linewidth=2)
hline(bot_tp,       "💰 TP $2,580",       color=color.new(color.lime,   0),  linestyle=hline.style_solid,  linewidth=2)

// ══ CHRONOS-2 FORECAST LINES (projected from current bar) ══
isLast = barstate.islast
var line[] med_lines  = array.new_line()
var line[] band_lines = array.new_line()
var label fc_label    = na

if isLast
    // Draw 12 forecast candles (each = 4H)
    for i = 0 to array.size(med_fc) - 1
        x1 = bar_index + i
        x2 = bar_index + i + 1
        med  = array.get(med_fc,  i)
        lo   = array.get(low_fc,  i)
        hi   = array.get(high_fc, i)
        // Median line — gold
        array.push(med_lines,  line.new(x1, med, x2, med, color=color.new(color.yellow, 20), width=2))
        // High band — green
        array.push(band_lines, line.new(x1, hi,  x2, hi,  color=color.new(color.green,  50), width=1, style=line.style_dashed))
        // Low band — red
        array.push(band_lines, line.new(x1, lo,  x2, lo,  color=color.new(color.red,    50), width=1, style=line.style_dashed))
        // Vertical connector every 3 steps
        if i % 3 == 0
            array.push(band_lines, line.new(x1, lo, x1, hi, color=color.new(color.gray, 70), width=1, style=line.style_dotted))
    
    // Summary label at end of forecast
    fc_end_med = array.get(med_fc,  11)
    fc_end_hi  = array.get(high_fc, 11)
    lbl_color  = fc_end_med > close ? color.new(color.green, 10) : color.new(color.red, 10)
    fc_label  := label.new(bar_index + 13, fc_end_hi * 1.003,
        "Chronos-2 +48h\\n" +
        "Med: $${sc[11].median}\\n" +
        "High: $${sc[11].high}\\n" +
        "Low: $${sc[11].low}\\n" +
        "${trend12} ${pct12}%",
        color=lbl_color, textcolor=color.white, style=label.style_label_left, size=size.normal)

// ══ INFO TABLE ══
var table t = table.new(position.top_right, 2, 7, bgcolor=color.new(color.black, 20), border_width=1)
if barstate.islast
    table.cell(t, 0, 0, "🤖 HERMES ETH DESK",     text_color=color.yellow, text_size=size.normal, bgcolor=color.new(color.navy,20))
    table.cell(t, 1, 0, "BOT B — GRID LONG",       text_color=color.yellow, text_size=size.normal, bgcolor=color.new(color.navy,20))
    table.cell(t, 0, 1, "Current Price",            text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 1, "$" + str.tostring(close, "#.00"), text_color=color.aqua, text_size=size.small)
    table.cell(t, 0, 2, "Bot B Trigger",            text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 2, "${triggerMsg}",            text_color=close >= 2350 ? color.lime : color.orange, text_size=size.small)
    table.cell(t, 0, 3, "Chronos +4h Median",       text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 3, "$${sc[0].median}",         text_color=color.yellow, text_size=size.small)
    table.cell(t, 0, 4, "Chronos +48h Median",      text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 4, "$${sc[11].median} (${trend12})", text_color=${sc[11].median > last} ? color.lime : color.red, text_size=size.small)
    table.cell(t, 0, 5, "Grid Zone",                text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 5, "$2,150 — $2,500",          text_color=color.aqua,   text_size=size.small)
    table.cell(t, 0, 6, "Stop / TP",                text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 6, "SL $2,050 / TP $2,580",   text_color=color.lime,   text_size=size.small)
`;
}

// Build Pine Script for Chart 2 — BTC opportunity / prediction view
function buildBTCPine(fc) {
  const btc = fc.BTC;
  const sc  = btc.scenarios;
  const last = btc.last;
  
  const medians = sc.map(s => s.median.toFixed(2)).join(', ');
  const lows    = sc.map(s => s.low.toFixed(2)).join(', ');
  const highs   = sc.map(s => s.high.toFixed(2)).join(', ');
  const trend12 = sc[11].median > last ? '▲ BULLISH' : '▼ BEARISH';
  const pct12   = ((sc[11].median - last) / last * 100).toFixed(2);
  const triggerDist = (78100 - last).toFixed(0);
  const triggerMsg  = last >= 78100 ? '🚀 ABOVE TRIGGER — DEPLOY BOT C NOW' : `${triggerDist > 0 ? triggerDist + ' below' : 'above'} $78,100`;

  return `//@version=5
indicator("🤖 Hermes — BTC Bot C Trigger + Chronos-2 Predictions", overlay=true, max_lines_count=50, max_labels_count=50)

// ══ CHRONOS-2 FORECAST DATA (live run ${new Date().toISOString().slice(0,16)}) ══
// Last close: $${last}  |  48h outlook: ${trend12} ${pct12}%

var float[] med_fc  = array.from(${medians})
var float[] low_fc  = array.from(${lows})
var float[] high_fc = array.from(${highs})

// ══ BOT C TRIGGER LEVELS ══
bot_trigger  = 78100.0
bot_grid_top = 84000.0
bot_grid_bot = 72000.0
bot_sl       = 71500.0
bot_tp       = 83500.0

hline(bot_trigger,  "🚀 Deploy Trigger $78,100", color=color.new(color.yellow, 0),  linestyle=hline.style_dashed, linewidth=3)
hline(bot_grid_top, "Grid Top $84,000",          color=color.new(color.green,  30), linestyle=hline.style_dashed, linewidth=1)
hline(bot_grid_bot, "Grid Low $72,000",          color=color.new(color.orange, 30), linestyle=hline.style_dashed, linewidth=1)
hline(bot_sl,       "🛑 Stop Loss $71,500",      color=color.new(color.red,    0),  linestyle=hline.style_solid,  linewidth=2)
hline(bot_tp,       "💰 TP $83,500",             color=color.new(color.lime,   0),  linestyle=hline.style_solid,  linewidth=2)

// ══ CHRONOS-2 FORECAST LINES ══
isLast = barstate.islast
var line[] med_lines  = array.new_line()
var line[] band_lines = array.new_line()
var label fc_label    = na

if isLast
    for i = 0 to array.size(med_fc) - 1
        x1  = bar_index + i
        x2  = bar_index + i + 1
        med = array.get(med_fc,  i)
        lo  = array.get(low_fc,  i)
        hi  = array.get(high_fc, i)
        array.push(med_lines,  line.new(x1, med, x2, med, color=color.new(color.yellow, 20), width=2))
        array.push(band_lines, line.new(x1, hi,  x2, hi,  color=color.new(color.green,  50), width=1, style=line.style_dashed))
        array.push(band_lines, line.new(x1, lo,  x2, lo,  color=color.new(color.red,    50), width=1, style=line.style_dashed))
        if i % 3 == 0
            array.push(band_lines, line.new(x1, lo, x1, hi, color=color.new(color.gray, 70), width=1, style=line.style_dotted))

    fc_end_med = array.get(med_fc,  11)
    fc_end_hi  = array.get(high_fc, 11)
    lbl_color  = fc_end_med > close ? color.new(color.green, 10) : color.new(color.red, 10)
    fc_label  := label.new(bar_index + 13, fc_end_hi * 1.003,
        "Chronos-2 +48h\\n" +
        "Med: $${sc[11].median}\\n" +
        "High: $${sc[11].high}\\n" +
        "Low: $${sc[11].low}\\n" +
        "${trend12} ${pct12}%",
        color=lbl_color, textcolor=color.white, style=label.style_label_left, size=size.normal)

// ══ INFO TABLE ══
var table t = table.new(position.top_right, 2, 8, bgcolor=color.new(color.black, 20), border_width=1)
if barstate.islast
    table.cell(t, 0, 0, "🤖 HERMES BTC DESK",         text_color=color.yellow, text_size=size.normal, bgcolor=color.new(color.navy,20))
    table.cell(t, 1, 0, "BOT C — GRID TRIGGER",        text_color=color.yellow, text_size=size.normal, bgcolor=color.new(color.navy,20))
    table.cell(t, 0, 1, "Current Price",                text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 1, "$" + str.tostring(close, "#.00"), text_color=color.aqua, text_size=size.small)
    table.cell(t, 0, 2, "Bot C Trigger",                text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 2, "${triggerMsg}",                text_color=close >= 78100 ? color.lime : color.orange, text_size=size.small)
    table.cell(t, 0, 3, "Chronos +4h",                  text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 3, "M:$${sc[0].median} L:$${sc[0].low} H:$${sc[0].high}", text_color=color.yellow, text_size=size.small)
    table.cell(t, 0, 4, "Chronos +24h",                 text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 4, "M:$${sc[5].median}",           text_color=color.yellow, text_size=size.small)
    table.cell(t, 0, 5, "Chronos +48h",                 text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 5, "$${sc[11].median} (${trend12})", text_color=${sc[11].median > last} ? color.lime : color.red, text_size=size.small)
    table.cell(t, 0, 6, "Grid Zone",                    text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 6, "$72,000 — $84,000",            text_color=color.aqua,   text_size=size.small)
    table.cell(t, 0, 7, "Deploy Signal",                 text_color=color.white,  text_size=size.small)
    table.cell(t, 1, 7, close >= 78100 ? "✅ FIRE BOT C" : "⏳ WAITING",        text_color=close >= 78100 ? color.lime : color.orange, text_size=size.small)
`;
}

async function main() {
  await call('initialize', { protocolVersion:'2024-11-05', capabilities:{}, clientInfo:{name:'hermes-pine',version:'1'} });
  await call('notifications/initialized', {});

  console.log('=== INJECTING CHRONOS-2 PINE SCRIPTS ===\n');

  // ── CHART 1: ETH view ──
  console.log('Chart 1: Setting ETH/USDT 4H...');
  await tv('chart_set_symbol', { symbol: 'BINANCE:ETHUSDTPERP' });
  await sleep(2500);
  await tv('chart_set_timeframe', { timeframe: '240' });
  await sleep(2000);

  // Clear old drawings
  await tv('draw_clear', {});
  await sleep(500);

  // Redraw Bot B levels cleanly
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 2350 },  color: '#FFD700', text: '🔥 BOT B TRIGGER $2,350 — needs 4H close above', linewidth: 2, linestyle: 'dashed' });
  await sleep(400);
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 2500 },  color: '#00E676', text: 'Grid Top $2,500', linewidth: 1, linestyle: 'dashed' });
  await sleep(400);
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 2150 },  color: '#FF9800', text: 'Grid Low $2,150', linewidth: 1, linestyle: 'dashed' });
  await sleep(400);
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 2050 },  color: '#FF1744', text: '🛑 STOP LOSS $2,050', linewidth: 2 });
  await sleep(400);
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 2580 },  color: '#69F0AE', text: '💰 TAKE PROFIT $2,580', linewidth: 2 });
  await sleep(400);

  // Open Pine Editor and inject ETH script
  console.log('Opening Pine Editor for ETH chart...');
  await tv('ui_open_panel', { panel: 'pine-editor' });
  await sleep(2000);

  await tv('pine_new', { type: 'indicator' });
  await sleep(1500);

  const ethPine = buildETHPine(forecast);
  await tv('pine_set_source', { source: ethPine });
  await sleep(1500);

  const compileResult1 = await tv('pine_smart_compile', {});
  console.log('ETH Pine compile:', JSON.stringify(compileResult1).substring(0,200));
  await sleep(2000);

  // Screenshot Chart 1 with Pine overlay
  const ss1 = await tv('capture_screenshot', { region: 'chart' });
  console.log('CHART1_PATH:', ss1.file_path || ss1);
  await sleep(1000);

  // ── CHART 2: BTC opportunity view ──
  console.log('\nChart 2: Setting BTC/USDT 4H...');
  await tv('chart_set_symbol', { symbol: 'BINANCE:BTCUSDTPERP' });
  await sleep(2500);
  await tv('chart_set_timeframe', { timeframe: '240' });
  await sleep(2000);

  // Clear drawings, add BTC levels
  await tv('draw_clear', {});
  await sleep(500);
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 78100 }, color: '#FFD700', text: '🚀 BOT C TRIGGER $78,100 — deploy grid on break+hold', linewidth: 3, linestyle: 'dashed' });
  await sleep(400);
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 84000 }, color: '#00E676', text: 'Grid Top $84,000 / TP $83,500', linewidth: 1, linestyle: 'dashed' });
  await sleep(400);
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 72000 }, color: '#FF9800', text: 'Grid Low $72,000', linewidth: 1, linestyle: 'dashed' });
  await sleep(400);
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 71500 }, color: '#FF1744', text: '🛑 STOP LOSS $71,500', linewidth: 2 });
  await sleep(400);
  await tv('draw_shape', { type: 'horizontal_line', point: { price: 83500 }, color: '#69F0AE', text: '💰 TAKE PROFIT $83,500', linewidth: 2 });
  await sleep(400);

  // Inject BTC Pine script
  console.log('Injecting BTC Pine script...');
  await tv('pine_new', { type: 'indicator' });
  await sleep(1500);

  const btcPine = buildBTCPine(forecast);
  await tv('pine_set_source', { source: btcPine });
  await sleep(1500);

  const compileResult2 = await tv('pine_smart_compile', {});
  console.log('BTC Pine compile:', JSON.stringify(compileResult2).substring(0,200));
  await sleep(2000);

  // Screenshot Chart 2
  const ss2 = await tv('capture_screenshot', { region: 'chart' });
  console.log('CHART2_PATH:', ss2.file_path || ss2);

  console.log('\n=== DONE ===');
  console.log('ETH forecast next 48h: median $' + forecast.ETH.scenarios[11].median);
  console.log('BTC forecast next 48h: median $' + forecast.BTC.scenarios[11].median);
  console.log('SOL forecast next 48h: median $' + forecast.SOL.scenarios[11].median);

  proc.kill();
}

main().catch(e => { console.error('ERROR:', e.message, e.stack); proc.kill(); process.exit(1); });
